MW-3 Explanation
Codubee/PetFinderMW3-4 pull request #2
Opened 2021-03-27 01:09 UTC by chelseah02

* **Please check if the PR fulfills these requirements**
- [x] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
Adds Explanation component.

* **What is the current behavior? What does the code do before you made the new changes?** 
Currently, there is a header "Landing Page" displayed. 

* **What is the new behavior?**
A jumbotron is inserted that welcomes the user and briefly introduces the project.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
No

* **Other information**:

2021-03-28 22:42 UTC, Codubee commented on frontend/src/components/Explanation.js
> +            </p>
Please remove this as we are not going to use it.

2021-03-28 22:43 UTC, Codubee commented on frontend/src/components/Explanation.js
> +} // end function Explanation()
Consider removing these comments as they are not useful for the reader.

2021-03-28 22:44 UTC, Codubee commented on frontend/src/views/LandingPage.js
> +            }
You can remove the comment here as well and the component does not need to be inside of curly braces.

2021-03-28 22:44 UTC, Codubee requested changes
Great work Chelsea. I left some comments for discussion.

2021-03-29 19:42 UTC, evanjelica commented on frontend/src/components/Explanation.js
> +                The furry friend finder is a solution to help shelter animals in Dallas get adopted. It matches a person looking for a pet with a pet that is at an animal shelter. Take a look at a pi
Miguel already addressed everything else. One minor change would be to capitalize 'Furry Friend Finder' since it is the name of our project/app

2021-04-02 20:19 UTC, Codubee approved these changes

2021-04-02 20:20 UTC, merged